
--drop table
DROP TABLE EMPLOYEE;

--create table
CREATE TABLE EMPLOYEE(
	ID BIGINT PRIMARY KEY,
	LAST_NAME VARCHAR(50) NOT NULL,
	FIRST_NAME VARCHAR(50)  NOT NULL
);

--insert test data
INSERT INTO EMPLOYEE(ID, LAST_NAME, FIRST_NAME)
VALUES(1, 'George', 'Mike');

INSERT INTO EMPLOYEE(ID, LAST_NAME, FIRST_NAME)
VALUES(2, 'Mary', 'Anne');

